remedial2/Remedial2P/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

remedial2/core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('create/team/', views.CreateTeam.as_view(), name="create_team"),
    path('list/team/', views.ListTeam.as_view(), name="list_team"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name="update_team"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name="delete_team"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name="detail_team"),

    path('create/stadium/', views.CreateStadium.as_view(), name="create_stadium"),
    path('list/stadium/', views.ListStadium.as_view(), name="list_stadium"),
    path('update/stadium/<int:pk>/', views.UpdateStadium.as_view(), name="update_stadium"),
    path('delete/stadium/<int:pk>/', views.DeleteStadium.as_view(), name="delete_stadium"),
    path('detail/team/<int:pk>/', views.DetailStadium.as_view(), name="detail_stadium"),

    path('create/city/', views.CreateCity.as_view(), name="create_city"),
    path('list/city/', views.ListCity.as_view(), name="list_city"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name="update_city"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name="delete_city"),
    path('detail/team/<int:pk>/', views.DetailCity.as_view(), name="detail_city"),

    path('create/player/', views.CreatePlayer.as_view(), name="create_player"),
    path('list/player/', views.ListPlayer.as_view(), name="list_player"),
    path('update/player/<int:pk>/', views.UpdatePlayer.as_view(), name="update_player"),
    path('delete/player/<int:pk>/', views.DeletePlayer.as_view(), name="delete_player"),
    path('detail/team/<int:pk>/', views.DetailPlayer.as_view(), name="detail_player"),

]

remedial2/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Inicio.as_view(), name="inicio"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

remedial2/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">NFL</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if request.user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home:inicio' %}">Home
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:list_city' %}">Citys</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:list_player' %}">Players</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:list_stadium'%}">Stadiums</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:list_team' %}">Teams</a>
          </div>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-sm-2" type="search" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
        <div class="dropdown">
          <button class="btn" data-bs-toggle="dropdown" aria-expanded="false" style="border-radius: 10px; background-color: transparent; margin-left: 15px;">
            <img src="/static/imagen/usuario.png" alt="lupa" width="40px">
          </button>
          <ul class="dropdown-menu dropdown-menu-lg-end text-center" style="background-color: white;">
            <p style="color: black; font-size: 30px;"> {{ user }} </p>
            <a href="{% url 'home:logout' %}" class="btn btn-outline-danger" style="border-radius: 10px;">LogOut</a>
          </ul>
        </div>
      </div>
      {% endif %}
    </div>
  </nav>
  {% block content %} {% endblock content %}
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>