remedial2/Remedial2P/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

remedial2/core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('create/team/', views.CreateTeam.as_view(), name="create_team"),
    path('list/team/', views.ListTeam.as_view(), name="list_team"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name="update_team"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name="delete_team"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name="detail_team"),

    path('create/stadium/', views.CreateStadium.as_view(), name="create_stadium"),
    path('list/stadium/', views.ListStadium.as_view(), name="list_stadium"),
    path('update/stadium/<int:pk>/', views.UpdateStadium.as_view(), name="update_stadium"),
    path('delete/stadium/<int:pk>/', views.DeleteStadium.as_view(), name="delete_stadium"),
    path('detail/team/<int:pk>/', views.DetailStadium.as_view(), name="detail_stadium"),

    path('create/city/', views.CreateCity.as_view(), name="create_city"),
    path('list/city/', views.ListCity.as_view(), name="list_city"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name="update_city"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name="delete_city"),
    path('detail/team/<int:pk>/', views.DetailCity.as_view(), name="detail_city"),

    path('create/player/', views.CreatePlayer.as_view(), name="create_player"),
    path('list/player/', views.ListPlayer.as_view(), name="list_player"),
    path('update/player/<int:pk>/', views.UpdatePlayer.as_view(), name="update_player"),
    path('delete/player/<int:pk>/', views.DeletePlayer.as_view(), name="delete_player"),
    path('detail/team/<int:pk>/', views.DetailPlayer.as_view(), name="detail_player"),

]

remedial2/core/models.py
from django.db import models

# Create your models here.

class City(models.Model):
    city_name = models.CharField(max_length=20, default="Nombre de la ciudad")
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.city_name
    
class Team(models.Model):
    venue = models.ForeignKey(City, on_delete=models.CASCADE, null=True)
    team_name = models.CharField(max_length=50, default="Nombre del equipo")
    players = models.IntegerField(default=0)
    director = models.CharField(max_length=30, default="Director a cargo")
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.team_name

class Player(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    player_name = models.CharField(max_length=50, default="Nombre del jugador")
    number = models.IntegerField(default=0)
    position = models.CharField(max_length=30, default="Posicion del jugador")

    def __str__(self):
        return self.player_name

class Stadium(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True)
    stadium_name = models.CharField(max_length=50, default="Nombre del estadio")
    capacity = models.IntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.stadium_name

remedial2/core/forms.py
from django import forms

from .models import Team, Stadium, City, Player

# T E A M
class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            "venue",
            "team_name",
            "players",
            "director",
        ]
        widgets = {
            "venue": forms.Select(attrs={"type":"form-select", "class":"form-control"}),
            "team_name": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
            "players": forms.NumberInput(attrs={"type":"form-select", "class":"form-control"}),
            "director": forms.TextInput(attrs={"type":"form-select", "class":"form-control"})
        }
    
class UpdateTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            "venue",
            "team_name",
            "players",
            "director",
        ]
        widgets = {
            "venue": forms.Select(attrs={"type":"form-select", "class":"form-control"}),
            "team_name": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
            "players": forms.NumberInput(attrs={"type":"form-select", "class":"form-control"}),
            "director": forms.TextInput(attrs={"type":"form-select", "class":"form-control"})
        }

#-----------------------------------------------------------------------------------------------------------------#

# S T A D I U M
class StadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = [
            "team",
            "city",
            "stadium_name",
            "capacity",
        ]
        widgets = {
            "team": forms.Select(attrs={"type":"form-select", "class":"form-control"}),
            "city": forms.Select(attrs={"type":"form-select", "class":"form-control"}),
            "stadium_name": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
            "capacity": forms.NumberInput(attrs={"type":"number", "class":"form-control"})
        }

class UpdateStadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = [
            "team",
            "city",
            "stadium_name",
            "capacity",
        ]
        widgets = {
            "team": forms.Select(attrs={"type":"form-select", "class":"form-control"}),
            "city": forms.Select(attrs={"type":"form-select", "class":"form-control"}),
            "stadium_name": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
            "capacity": forms.NumberInput(attrs={"type":"number", "class":"form-control"})
        }

# ------------------------------------------------------------------------------------------------------------------#

# C I T Y
class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = [
            "city_name",
        ]
        widgets = {
            "city_name": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
        }

class UpdateCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = [
            "city_name",
        ]
        widgets = {
            "city_name": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
        }

# ------------------------------------------------------------------------------------------------------------------#

# P L A Y E R
class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = [
            "team",
            "player_name",
            "number",
            "position",
        ]
        widgets = {
            "team": forms.Select(attrs={"type":"form-select", "class":"form-control"}),
            "player_name": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
            "number": forms.NumberInput(attrs={"type":"form-select", "class":"form-control"}),
            "position": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
        }

class UpdatePlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = [
            "team",
            "player_name",
            "number",
            "position",
        ]
        widgets = {
            "team": forms.Select(attrs={"type":"form-select", "class":"form-control"}),
            "player_name": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
            "number": forms.NumberInput(attrs={"type":"form-select", "class":"form-control"}),
            "position": forms.TextInput(attrs={"type":"form-select", "class":"form-control"}),
        }

remedial2/core/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views import generic

from .models import Team, Stadium, City, Player
from .forms import TeamForm, UpdateTeamForm, StadiumForm, UpdateStadiumForm, CityForm, UpdateCityForm, PlayerForm, UpdatePlayerForm

# Create your views here.

### T E A M ###
  
# list
class ListTeam(generic.View):
    template_name = "core/team/list_team.html"
    context = {}

    def get(self, request, *args, **kwargs):
        teams = Team.objects.filter(status=True)
        self.context = {
            "teams": teams
        }
        return render(request, self.template_name, self.context)

# create
class CreateTeam(generic.CreateView):
    template_name = "core/team/create_team.html"
    context = {}
    form_class = TeamForm
    success_url = reverse_lazy("core:list_team")

# update
class UpdateTeam(generic.UpdateView):
    template_name = "core/team/update_team.html"
    model = Team
    form_class = UpdateTeamForm
    success_url = reverse_lazy("core:list_team")

# delete
class DeleteTeam(generic.DeleteView):
    template_name = "core/team/delete_team.html"
    model = Team
    success_url = reverse_lazy("core:list_team")

# detail
class DetailTeam(generic.DetailView):
    template_name = "core/team/detail_team.html"
    model = Team
    success_url = reverse_lazy("core:list_team")

#-------------------------------------------------------------------------#

### S T A D I U M ###
class ListStadium(generic.View):
    template_name = "core/stadium/list_stadium.html"
    context = {}

    def get(self, request, *args, **kwargs):
        stadiums = Stadium.objects.filter(status=True)
        self.context = {
            "stadiums": stadiums
        }
        return render(request, self.template_name, self.context)

# create
class CreateStadium(generic.CreateView):
    template_name = "core/stadium/create_stadium.html"
    context = {}
    form_class = StadiumForm
    success_url = reverse_lazy("core:list_stadium")

# update
class UpdateStadium(generic.UpdateView):
    template_name = "core/stadium/update_stadium.html"
    model = Stadium
    form_class = UpdateStadiumForm
    success_url = reverse_lazy("core:list_stadium")

# delete
class DeleteStadium(generic.DeleteView):
    template_name = "core/stadium/delete_stadium.html"
    model = Stadium
    success_url = reverse_lazy("core:list_stadium")

# detail
class DetailStadium(generic.DetailView):
    template_name = "core/stadium/detail_stadium.html"
    model = Stadium
    success_url = reverse_lazy("core:list_stadium")

#-------------------------------------------------------------------------#

### C I T Y ###

# list
class ListCity(generic.View):
    template_name = "core/city/list_city.html"
    context = {}

    def get(self, request, *args, **kwargs):
        citys = City.objects.filter(status=True)
        self.context = {
            "citys": citys
        }
        return render(request, self.template_name, self.context)

# create
class CreateCity(generic.CreateView):
    template_name = "core/city/create_city.html"
    context = {}
    form_class = CityForm
    success_url = reverse_lazy("core:list_city")

# update
class UpdateCity(generic.UpdateView):
    template_name = "core/city/update_city.html"
    model = City
    form_class = UpdateCityForm
    success_url = reverse_lazy("core:list_city")

# delete
class DeleteCity(generic.DeleteView):
    template_name = "core/city/delete_city.html"
    model = City
    success_url = reverse_lazy("core:list_city")

# detail
class DetailCity(generic.DetailView):
    template_name = "core/city/detail_city.html"
    model = City
    success_url = reverse_lazy("core:list_city")

#-------------------------------------------------------------------------#

### P L A Y E R ###

# list
class ListPlayer(generic.View):
    template_name = "core/player/list_player.html"
    context = {}

    def get(self, request, *args, **kwargs):
        players = City.objects.filter(status=True)
        self.context = {
            "players": players
        }
        return render(request, self.template_name, self.context)

# create
class CreatePlayer(generic.CreateView):
    template_name = "core/player/create_player.html"
    context = {}
    form_class = PlayerForm
    success_url = reverse_lazy("core:list_player")

# update
class UpdatePlayer(generic.UpdateView):
    template_name = "core/player/update_player.html"
    model = Player
    form_class = UpdatePlayerForm
    success_url = reverse_lazy("core:list_player")

# delete
class DeletePlayer(generic.DeleteView):
    template_name = "core/player/delete_player.html"
    model = Player
    success_url = reverse_lazy("core:list_player")

#detail
class DetailPlayer(generic.DetailView):
    template_name = "core/player/detail_player.html"
    model = Player
    success_url = reverse_lazy("core:list_player")

remedial2/templates/core/team/create_team.html
{% extends "base/base.html" %}

{% block title %} CREATE TEAM VIEW {% endblock title %}

{% block content %}
    <div class="container text-center">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form action="" method="post" class="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <br>
                    <button type="submit" class="btn btn-outline-success" style="border-radius: 10px; margin-right: 40px;">Create</button>
                    <a href="{% url 'core:list_team' %}" class="btn btn-outline-danger" style="border-radius: 10px;">Cancel</a>
                </form>  
            </div>
        </div>
    </div>
{% endblock content %}

remedial2/templates/core/team/delete_team.html
{% extends "base/base.html" %}

{% block title %}
    DELETE TEAM VIEW
{% endblock title %}

{% block content %}
<div class="container text-center">
  <div class="row">
      <div class="col-md-6 offset-md-3">
        <form action="" method="post">
            {% csrf_token %}
            <div class="card border-danger mb-3" style="max-width: 20rem;">
                <div class="card-header">Delete</div>
                <div class="card-body">
                  <h4 class="card-title">{{ object.player_name }}</h4>
                  <p><h1>¿Realmente deseas eliminar esto?</h1></p>
                  <button type="submit" class="btn btn-danger">Delete</button>
                  <a href="{% url 'core:list_team' %}" class="btn btn-warning">Cancel</a>
                </div>
              </div>
        </form>
      </div>
  </div>
</div>
{% endblock content %}

remedial2/templates/core/team/detail_team.html
{% extends "base/base.html" %}

{% block title %}
    DETAIL TEAM VIEW
{% endblock title %}

{% block content %}
<br><br>
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ team.team_name }} 
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>LOCACION: </strong> {{ team.venue }} <br>
          <strong>NOMBRE DEL EQUIPO: </strong> {{ team.team_name }} <br>
          <strong>JUGADORES: </strong>$ {{ team.players}}
          <br><br>
          <strong>DIRECTOR: </strong> {{ team.director }}
          <br>
        </div>
      </div>
    </div>
  </div>
  <br>
<a href="{% url 'core:list_team' %}" class="btn btn-outline-warning" style="border-radius: 10px;">Back To List</a>
{% endblock content %}

remedial2/templates/core/team/list_team.html
{% extends "base/base.html" %}

{% block title %} LIST TEAM VIEW {% endblock title %}

{% block content %}
<br> {% load static %}
{% if request.user.is_staff or request.user.is_superuser %}
<a href="{% url 'core:create_team' %}" class="btn btn-outline-success form-control" style="border-radius: 10px;">Create</a>
    <br><br>
        <table class="table table-striped table-hover">
            <thead class="table-primary">
                <th>ID</th>
                <th>NOMBRE DEL EQUIPO</th>
                <th>ESTADO</th>
                <th></th>
                <th>ACTIONS</th>
                <th></th>
            </thead>
            <tbody>
                {% for team in teams %}
                    <tr>
                        <td>{{ team.id }}</td>
                        <td>{{ team.team_name }}</td>
                        <td>{{ team.status }}</td>
                        <td><a href="{% url 'core:update_team' team.id %}" class="btn btn-outline-warning" style="border-radius: 10px;">Update</a></td>
                        <td><a href="{% url 'core:delete_team' team.id %}" class="btn btn-outline-danger" style="border-radius: 10px;">Delete</a></td>
                        <td><a href="{% url 'core:detail_team' team.id %}" class="btn btn-outline-info" style="border-radius: 10px;">Detail</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock content %}

remedial2/templates/core/team/update_team.html
{% extends "base/base.html" %}

{% block title %}
    UPDATE TEAM VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Update</button>
        <br>
        <a href="{% url 'core:list_team' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}